apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: db-slave
  name: db-slave
  namespace: bootcamp
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: db-slave
