apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: data-replica
  name: data-replica
  namespace: bootcamp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
