apiVersion: v1
data:
  server.crt: "Certificate:

    \    Data:

    \        Version: 3 (0x2)

    \        Serial Number: 4096 (0x1000)

    \        Signature Algorithm: sha256WithRSAEncryption

    \        Issuer: C=GB, ST=Cambridgeshire, L=Cambridge, O=MyLab, CN=MyLab

    \        Validity

    \            Not Before: Nov 19 21:19:53 2025 GMT

    \            Not After : Nov 17 21:19:53 2035 GMT

    \        Subject: C=GB, ST=Cambridgeshire, O=MyLab, CN=bootcamp.portaone.com

    \        Subject Public Key Info:

    \            Public Key Algorithm: rsaEncryption

    \                Public-Key: (2048 bit)

    \                Modulus:

    \                    00:ec:ee:c8:f0:91:4b:6f:c9:ca:a5:52:09:14:3d:

    \                    1e:79:13:5d:0a:ca:7c:d3:ce:03:6d:38:4b:1b:34:

    \                    6a:0e:af:3d:c8:37:2a:d0:84:21:b5:f8:5c:8f:59:

    \                    42:8f:59:eb:f6:7c:e7:44:7c:8c:82:57:6d:ab:78:

    \                    6c:67:c1:fe:08:56:d9:32:0a:b5:27:2d:45:28:e5:

    \                    49:c4:7a:6c:e7:a9:70:e6:49:c5:c5:1e:0f:54:2f:

    \                    07:c0:60:97:60:ee:c6:be:ba:49:94:b3:cf:02:d0:

    \                    97:af:96:8b:2b:fa:da:3e:ab:7e:03:0c:f7:b3:b6:

    \                    86:7c:3b:67:ac:e3:b7:a6:dc:e0:a3:3a:90:68:81:

    \                    79:38:55:ec:f8:89:8e:a8:4e:f1:05:4b:19:38:b9:

    \                    e1:75:e6:4d:cb:e2:3d:c3:42:8f:1b:e5:29:34:1e:

    \                    d2:96:af:9d:86:33:da:90:b1:bd:3e:3a:d9:64:69:

    \                    1c:be:aa:a2:03:f8:a8:3a:0c:31:bc:0d:35:51:59:

    \                    2b:00:35:40:0d:2c:d2:f6:ac:cf:40:c7:38:c1:85:

    \                    15:4a:d3:43:f8:30:df:44:ad:ce:e9:16:70:38:47:

    \                    aa:bf:cf:18:47:46:ca:71:bb:20:26:66:df:a1:ea:

    \                    20:8d:e1:88:a2:ba:ad:bc:c8:91:e6:32:c6:3c:68:

    \                    9c:4d

    \                Exponent: 65537 (0x10001)

    \        X509v3 extensions:

    \            X509v3 Basic Constraints:\ 

    \                CA:FALSE

    \            X509v3 Key Usage:\ 

    \                Digital Signature, Key Encipherment

    \            X509v3 Extended Key Usage:\ 

    \                TLS Web Server Authentication, TLS Web Client Authentication

    \            X509v3 Subject Key Identifier:\ 

    \                4C:02:08:02:D4:31:4F:77:9E:F4:F3:1D:84:16:32:93:82:E9:86:6A

    \            X509v3 Authority Key Identifier:\ 

    \                3C:A6:77:0C:98:20:E5:D1:A7:C4:B9:D2:DE:54:57:1C:B1:4E:26:8C

    \            X509v3 Subject Alternative Name:\ 

    \                DNS:bootcamp.portaone.com

    \    Signature Algorithm: sha256WithRSAEncryption

    \    Signature Value:

    \        1e:9a:c6:f5:93:5c:ee:3d:22:5f:0c:2b:03:e2:db:65:8d:56:

    \        8b:a9:54:bd:20:84:04:fe:0e:e8:95:51:a6:b1:d3:d2:a8:9f:

    \        29:b4:82:c4:f3:18:a0:1c:fe:23:3a:05:e7:a4:bb:16:a9:0d:

    \        91:f3:8a:2e:7c:9a:ab:5b:18:97:52:77:8f:47:4f:00:a2:6b:

    \        d5:cb:44:4a:68:d8:e0:89:83:b8:8b:ba:a3:38:50:c1:6f:e8:

    \        a3:cb:84:f9:27:de:e0:04:a0:29:bd:a2:a4:41:bf:0f:3c:00:

    \        ed:83:d9:51:f3:58:65:94:a5:82:c3:1b:d0:47:26:6a:a2:b4:

    \        82:b6:67:eb:1e:f3:d8:a8:c5:ba:25:82:d3:14:36:fb:aa:d1:

    \        f2:fb:dc:d6:78:5d:96:f9:f8:39:ea:46:81:ca:d7:71:54:e7:

    \        4c:bb:3a:71:dc:e9:d6:0e:f3:5d:af:37:5d:dd:07:76:e5:bf:

    \        b3:c3:f1:a6:0f:26:f8:01:1e:34:1b:9e:2b:51:61:52:a0:47:

    \        a2:95:14:b8:c5:1e:1c:91:78:06:9d:df:29:47:9e:bb:85:46:

    \        73:71:88:57:68:a0:07:6c:5c:51:eb:2f:a2:0e:cb:fa:6b:23:

    \        98:53:ac:05:45:6c:6b:b3:c1:dd:02:d9:47:b8:ba:31:d3:c7:

    \        35:48:49:23:4a:62:86:47:62:c9:a1:2b:bb:2f:3e:1b:f3:bf:

    \        00:4a:1e:3a:d1:4f:70:ca:48:c9:91:1e:7f:5e:f3:47:11:7a:

    \        1d:a0:76:95:a2:e2:10:64:5e:35:1e:57:16:f3:5e:86:8a:bf:

    \        fc:fd:71:f2:23:7c:12:cf:e6:73:7b:05:88:79:6c:bf:c6:ed:

    \        87:a0:1f:c5:79:35:66:20:ff:51:25:31:88:bf:fd:98:a1:8d:

    \        db:b2:96:ac:46:8b:82:73:26:2d:a6:15:77:cf:17:96:dc:b8:

    \        83:7e:20:7a:74:b6:6e:43:78:7b:b8:e3:b5:f7:58:4e:4f:c7:

    \        37:9f:89:ff:73:1f:32:e7:7b:f5:7f:37:30:92:48:35:07:88:

    \        2c:c0:a9:49:08:c4:88:83:3b:84:df:d4:e0:e6:d7:f1:6f:be:

    \        36:67:be:ad:32:d4:17:2a:d5:59:9e:f7:2e:2c:ed:86:23:6b:

    \        e1:d1:e1:b3:ef:aa:e1:3c:85:ff:72:0a:0e:d9:db:2f:ef:09:

    \        5f:71:95:f3:f1:b7:0b:d4:a3:6a:22:b0:09:18:9d:a3:c0:fa:

    \        7e:bb:bc:70:53:40:23:1e:7a:76:83:c9:a9:4c:dd:05:46:1e:

    \        ec:47:ae:f9:f4:b4:c0:6b:6d:f9:82:09:6a:aa:ff:5e:74:0a:

    \        bf:05:37:c7:e7:31:b0:e8

    -----BEGIN CERTIFICATE-----

    MIIEyTCCArGgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwWjELMAkGA1UEBhMCR0Ix

    FzAVBgNVBAgMDkNhbWJyaWRnZXNoaXJlMRIwEAYDVQQHDAlDYW1icmlkZ2UxDjAM

    BgNVBAoMBU15TGFiMQ4wDAYDVQQDDAVNeUxhYjAeFw0yNTExMTkyMTE5NTNaFw0z

    NTExMTcyMTE5NTNaMFYxCzAJBgNVBAYTAkdCMRcwFQYDVQQIDA5DYW1icmlkZ2Vz

    aGlyZTEOMAwGA1UECgwFTXlMYWIxHjAcBgNVBAMMFWJvb3RjYW1wLnBvcnRhb25l

    LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOzuyPCRS2/JyqVS

    CRQ9HnkTXQrKfNPOA204Sxs0ag6vPcg3KtCEIbX4XI9ZQo9Z6/Z850R8jIJXbat4

    bGfB/ghW2TIKtSctRSjlScR6bOepcOZJxcUeD1QvB8Bgl2Duxr66SZSzzwLQl6+W

    iyv62j6rfgMM97O2hnw7Z6zjt6bc4KM6kGiBeThV7PiJjqhO8QVLGTi54XXmTcvi

    PcNCjxvlKTQe0pavnYYz2pCxvT462WRpHL6qogP4qDoMMbwNNVFZKwA1QA0s0vas

    z0DHOMGFFUrTQ/gw30StzukWcDhHqr/PGEdGynG7ICZm36HqII3hiKK6rbzIkeYy

    xjxonE0CAwEAAaOBnDCBmTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIFoDAdBgNVHSUE

    FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFEwCCALUMU93nvTzHYQW

    MpOC6YZqMB8GA1UdIwQYMBaAFDymdwyYIOXRp8S50t5UVxyxTiaMMCAGA1UdEQQZ

    MBeCFWJvb3RjYW1wLnBvcnRhb25lLmNvbTANBgkqhkiG9w0BAQsFAAOCAgEAHprG

    9ZNc7j0iXwwrA+LbZY1Wi6lUvSCEBP4O6JVRprHT0qifKbSCxPMYoBz+IzoF56S7

    FqkNkfOKLnyaq1sYl1J3j0dPAKJr1ctESmjY4ImDuIu6ozhQwW/oo8uE+Sfe4ASg

    Kb2ipEG/DzwA7YPZUfNYZZSlgsMb0EcmaqK0grZn6x7z2KjFuiWC0xQ2+6rR8vvc

    1nhdlvn4OepGgcrXcVTnTLs6cdzp1g7zXa83Xd0HduW/s8Pxpg8m+AEeNBueK1Fh

    UqBHopUUuMUeHJF4Bp3fKUeeu4VGc3GIV2igB2xcUesvog7L+msjmFOsBUVsa7PB

    3QLZR7i6MdPHNUhJI0pihkdiyaEruy8+G/O/AEoeOtFPcMpIyZEef17zRxF6HaB2

    laLiEGReNR5XFvNehoq//P1x8iN8Es/mc3sFiHlsv8bth6AfxXk1ZiD/USUxiL/9

    mKGN27KWrEaLgnMmLaYVd88Xlty4g34genS2bkN4e7jjtfdYTk/HN5+J/3MfMud7

    9X83MJJINQeILMCpSQjEiIM7hN/U4ObX8W++Nme+rTLUFyrVWZ73LizthiNr4dHh

    s++q4TyF/3IKDtnbL+8JX3GV8/G3C9SjaiKwCRido8D6fru8cFNAIx56doPJqUzd

    BUYe7Eeu+fS0wGtt+YIJaqr/XnQKvwU3x+cxsOg=

    -----END CERTIFICATE-----\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db-master
  name: db-master.crt
  namespace: bootcamp
