apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: nagios
  name: nagios
  namespace: bootcamp
spec:
  type: NodePort
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
    nodePort: 30090
  selector:
    io.kompose.service: nagios
