apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: bootcamp
  labels:
    io.kompose.service: all
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "GB7el63AVQyaq"
  MYSQL_ROOT_PASSWORD_SLAVE: "IlbzbgxiZTRgw"
  MYSQL_USER: "app_user"
  MYSQL_PASSWORD: "dbGiZAUWtInGP"
  REPLICA_USER: "replic"
  REPLICA_PASSWORD: "4QDIQ901zrr2l"
---

apiVersion: v1
kind: Secret
metadata:
  name: nagios-secrets
  namespace: bootcamp
  labels:
    io.kompose.service: all
type: Opaque
stringData:
  NAGIOSADMIN_USER: "admin"
  NAGIOSADMIN_PASS: "GKYZoYFtcBz00"
